name: CI

on:
  pull_request:
    branches:
      - 'main'
  push:
    branches:
      - 'main'

jobs:
  build:
    name: Test on OTP ${{ matrix.otp_version }} and ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        otp_version: ['27']
        rebar3_version: ['3.24']
        os: [ubuntu-latest]
    env:
      OTP_VERSION: ${{ matrix.otp_version }}
    steps:
    - uses: actions/checkout@v4
    - uses: erlef/setup-beam@v1
      with:
        otp-version: ${{ matrix.otp_version }}
        rebar3-version: ${{ matrix.rebar3_version }}
    - uses: actions/cache@v4
      name: Cache
      with:
        path: |
          _build
        key: ${{ runner.os }}-build-${{ matrix.otp_version }}-${{ hashFiles(format('rebar.lock')) }}-1
        restore-keys: |
          ${{ runner.os }}-build-${{ matrix.otp_version }}-1-

    - name: Compile
      run: rebar3 compile

    - name: Proper tests
      run: rebar3 as test proper

    - name: XRef
      run: rebar3 xref

    - name: Dialyzer
      run: rebar3 dialyzer
